name: Tests

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.201'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.3.3'
      - name: Run test on Linux
        shell: bash
        run: |
          set -o errexit -o pipefail -o nounset
          dotnet --version
          ./build.sh --stack linux
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.201'
      - uses: actions/checkout@v2
      - name: Run test on Windows
        run: |
          ./build.ps1 Test --stack Windows