name: Tests

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Run test on Linux
        shell: bash
        run: |
          set -o errexit -o pipefail -o nounset
          dotnet --version
          ./build.sh --stack linux
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test on Windows
        run: |
          ./build.ps1 Test --stack Windows